# -*- coding: utf-8 -*-
"""Logistic Regression_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LObiearM8hK6pOxUbyVFcRGR_PK9tTWe

# Logistic Regression on Titanic Dataset

## 📝 Titanic Dataset: Column Description

| Column         | Description |
|----------------|-------------|
| **PassengerId** | Unique ID assigned to each passenger. |
| **Survived**    | Target variable (0 = Did not survive, 1 = Survived). |
| **Pclass**      | Passenger class (1 = 1st class, 2 = 2nd class, 3 = 3rd class). |
| **Name**        | Name of the passenger. |
| **Sex**         | Gender of the passenger (male/female). |
| **Age**         | Age of the passenger in years. |
| **SibSp**       | Number of siblings/spouses aboard the ship. |
| **Parch**       | Number of parents/children aboard the ship. |
| **Ticket**      | Ticket number. |
| **Fare**        | Fare paid by the passenger. |
| **Cabin**       | Cabin number (many missing values). |
| **Embarked**    | Port of Embarkation (C = Cherbourg, Q = Queenstown, S = Southampton). |

## Load the data sets
"""

import pandas as pd
import numpy as np

#Load the Train data set
train_df =pd.read_csv("/content/Titanic_train.csv")

train_df

# Load the test data set
test_df =pd.read_csv("/content/Titanic_test.csv")

test_df

# Data types and non-null counts
train_df.info()

"""Survived' is our target column. It is binary (0 = No, 1 = Yes),  and will be used as is (int), since logistic regression expects numeric output.

 'Pclass', 'Sex', and 'Embarked' are actually categorical by meaning.
But we are not converting them to 'category' dtype here.
We'll handle them properly during preprocessing using encoding.
So it's okay to keep their original types for now.

### Dropping Irrelevant Columns:
"""

import re

# Define a function to extract titles from the Name column
def extract_title(name):
    # Use regular expression to extract titles like Mr, Mrs, Miss, etc.
    title = re.findall(r'(Mr|Mrs|Miss|Master|Dr|Rev|Col|Major|Capt|Mme|Ms)', name)
    if title:
        return title[0]
    else:
        return 'Unknown'

# Apply this function to both training and test data
train_df['Title'] = train_df['Name'].apply(extract_title)
test_df['Title'] = test_df['Name'].apply(extract_title)

# Drop irrelevant columns (PassengerId, Name, Ticket)
columns_to_drop = ['PassengerId', 'Name', 'Ticket']
train_df.drop(columns=columns_to_drop, axis=1, inplace=True)
test_df.drop(columns=columns_to_drop, axis=1, inplace=True)

train_df.head()

test_df.head()

"""Note:
- Dropped `PassengerId`, `Name`, and `Ticket` columns from both the training and test datasets as they do not provide useful information for the prediction task.
- The `Name` column was processed to extract titles, and the original column was dropped

### Finding Duplicates
"""

# Check for duplicate rows
duplicate_rows = train_df.duplicated()

# Count total duplicates
print("Total duplicate rows:", duplicate_rows.sum())

#Display duplicate rows in the training data
duplicate_train_data = train_df[train_df.duplicated()]
print("Duplicate rows in train data:")
print(duplicate_train_data)

"""### Remove Duplicates"""

train_df.drop_duplicates(inplace=True)

print("Total duplicate rows:", train_df.duplicated().sum())

"""### Finding Missing values"""

print("Missing values in trained data set:\n", train_df.isnull().sum())

print('The % of missing values in Age is', round((train_df['Age'].isnull().sum()/len(train_df))*100,1))
print('The % of missing values in Cabin is', round((train_df['Cabin'].isnull().sum()/len(train_df))*100,1))
print('The % of missing values in Embarked is', round((train_df['Embarked'].isnull().sum()/len(train_df))*100,1))

print("Missing values in test data set:\n", test_df.isnull().sum())

print('The % of missing values in Age in test data is', round((test_df['Age'].isnull().sum()/len(test_df))*100,1))
print('The % of missing values in Cabin in test datais', round((test_df['Cabin'].isnull().sum()/len(test_df))*100,1))
print('The % of missing values in Fare in test data is', round((train_df['Fare'].isnull().sum()/len(test_df))*100,1))

"""### Handling Missing Values:

Age: Impute with mean/median to handle based on skewness and dustribution of data

Embarked: Imputing with mode as it's a categorical feature with very few missing values.

Cabin: Droping due to high proportion of missing values (~77%), making it unreliable.
"""

# Impute missing Embarked with mode
train_df['Embarked'].fillna(train_df['Embarked'].mode()[0], inplace=True)

# Drop Cabin (too many missing values)
train_df.drop('Cabin', axis=1, inplace=True)

train_df.head()

"""### Droping Cabin column in test data set

Dropping Column from Training Data Based on Missing Values
Column 'Cabin' was dropped from the training dataset due to high percentage of missing values.

⚠️ Important: This same column must also be dropped from the test dataset before model evaluation/prediction to maintain consistency in feature space.
"""

test_df.drop('Cabin', axis=1, inplace=True)

test_df.head()

"""### Statistical Summary"""

train_df.describe()

"""### Visualization"""

train_df.info()

# List of numerical columns in your dataset
numerical_cols = ['Age', 'SibSp', 'Parch', 'Fare']
# List of Categorical columns in your dataset
categorical_cols=['Survived','Pclass','Sex','Embarked','Title']

import matplotlib.pyplot as plt
import seaborn as sns
import math

# Histograms for all numerical columns
num_plots = len(numerical_cols)
cols = 3
rows = math.ceil(num_plots / cols)

plt.figure(figsize=(cols * 5, rows * 4))
for i, col in enumerate(numerical_cols, 1):
    plt.subplot(rows, cols, i)
    sns.histplot(train_df[col].dropna(), kde=True)
    plt.title(f'Histogram: {col}')
plt.tight_layout()
plt.show()

# Boxplots for all numerical columns
plt.figure(figsize=(cols * 5, rows * 4))
for i, col in enumerate(numerical_cols, 1):
    plt.subplot(2, 2, i)
    sns.boxplot(x=train_df[col])
    plt.title(f'Boxplot: {col}')
plt.tight_layout()
plt.show()

# Bar plots for all categorical columns
cols = 3
rows = 2
plots_per_fig = cols * rows

for i in range(0, len(categorical_cols), plots_per_fig):
    batch = categorical_cols[i:i + plots_per_fig]
    plt.figure(figsize=(cols * 6, rows * 5))
    for j, col in enumerate(batch, 1):
        plt.subplot(rows, cols, j)
        sns.countplot(data=train_df, x=col, order=train_df[col].value_counts().index)
        plt.title(f'Bar Plot: {col}')
        plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

"""### Imputation of missing values

Normall we impute mean for normally ditributed data, median for skwed data

Here Age is slightly right skwed and Fare is right skewed so we are Imputing with median for Age column in both train and test data

Imputing median for Fare column in test data set only bacause missing value in test dat only
"""

# Impute missing values in 'Age' for both train and test datasets with train dataset median
train_df['Age'].fillna(train_df['Age'].median(), inplace=True)
test_df['Age'].fillna(train_df['Age'].median(), inplace=True)

# Impute missing value in 'Fare' for the test dataset with train dataset median
test_df['Fare'].fillna(train_df['Fare'].median(), inplace=True)

print("Missing values in trained data set:\n", train_df.isnull().sum())

print("Missing values in test data set:\n", test_df.isnull().sum())

"""### Finding Outliers"""

# Outliers for numerical columns
outlier_counts = {}

for col in numerical_cols:
    Q1 = train_df[col].quantile(0.25)
    Q3 = train_df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = train_df[(train_df[col] < lower_bound) | (train_df[col] > upper_bound)]
    outlier_counts[col] = len(outliers)

# Show outlier counts
print("Outlier Counts (Numerical):")
for col, count in outlier_counts.items():
    print(f"{col}: {count} outliers")

"""### Outlier Handling Strategy for Titanic (Logistic Regression)

- **Fare** is right-skewed with some very large values. We apply **log transformation** to normalize it.
- **Age** is mostly within reasonable limits. We keep it as is unless extreme wrong values are detected.
- **SibSp** and **Parch** represent real family sizes. No outlier handling needed.
- Final Decision:
  - Apply **log(1 + Fare)** transformation.
  - Proceed with Logistic Regression after preprocessing.

"""

# Apply log transformation to Fare column
train_df['Fare'] = np.log1p(train_df['Fare'])

# Apply log transformation to Fare column on test data
test_df['Fare'] = np.log1p(test_df['Fare'])

train_df.info()

"""### One Hot Encoding"""

train_df = pd.get_dummies(train_df, columns=["Sex", "Embarked", "Title"], drop_first=True)

train_df.head()

"""### One Hot Encoding on Test data"""

test_df = pd.get_dummies(test_df, columns=["Sex", "Embarked", "Title"], drop_first=True)

test_df.head()

"""Checking all column in train data is there in test data after one hot encoding, if not there add columns fill with 0's"""

train_features = train_df.drop("Survived", axis=1).columns

for col in train_features:
    if col not in test_df.columns:
        test_df[col] = 0

test_df.head()

"""### Feature Selection"""

# Heat msp for correlation

# Set up larger figure size for clarity
plt.figure(figsize=(16, 10))

# Optional: focus only on correlation with 'Survived'
corr_matrix = train_df.corr()

# Correlation with Target
corr_with_target = train_df.corr()['Survived'].sort_values(ascending=False)
print("Correlation with Target (Survived):\n", corr_with_target)

# Plot heatmap with refined settings
sns.heatmap(corr_matrix,
            annot=True,
            fmt=".2f",
            cmap="coolwarm",
            cbar_kws={'shrink': 0.8},
            square=True,
            linewidths=0.5)

plt.title("Correlation Heatmap of Titanic Features", fontsize=14)
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Features with very low correlation (absolute correlation < 0.10) provide minimal predictive value.
- Rare titles and certain categorical encodings were also weakly correlated or sparsely populated.

**Dropped the following weak features:**
- `Embarked_Q`, `Embarked_S`: Weak correlation with survival
- `SibSp`: Almost no relationship with target
- `Title_Col`, `Title_Dr`, `Title_Major`, `Title_Rev`, `Title_Unknown`: Rare or insignificant titles

This step helps simplify the model and potentially improve generalization.
"""

# List of weakly correlated columns
cols_to_drop = [
    "Embarked_Q",
    "Embarked_S",
    "SibSp",
    "Title_Col",
    "Title_Dr",
    "Title_Major",
    "Title_Rev",
    "Title_Unknown"
]

# Drop only the columns that actually exist in the train data set
train_df.drop(columns=[col for col in cols_to_drop if col in train_df.columns], inplace=True)

# Drop only the columns that actually exist in the test data set
test_df.drop(columns=[col for col in cols_to_drop if col in test_df.columns], inplace=True)

"""### Multi-Collinearity Check"""

train_df.info()

#  Drop Survived
X = train_df.drop('Survived', axis=1).copy()
y = train_df['Survived'].copy()

# Convert boolean columns to int (True → 1, False → 0)
X = X.astype({col: 'int64' for col in X.select_dtypes(include='bool').columns})

#  Convert all columns to numeric, if needed
X = X.apply(pd.to_numeric, errors='coerce')

# Step 4: VIF calculation
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

print(vif_data.sort_values(by="VIF", ascending=False))

# Drop Fare and Title_Mr to reduce multicollinearity
X = X.drop(['Fare', 'Title_Mr'], axis=1)

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

print("VIF after dropping Fare and Title_Mr:\n")
print(vif_data.sort_values(by="VIF", ascending=False))

# Extract 'Survived' column separately
y = train_df['Survived']

# Combine cleaned X with y
train_df = pd.concat([X, y], axis=1)

# Drop Fare and Title_Mr in test data
test_df = test_df.drop(['Fare', 'Title_Mr'], axis=1)

train_df.head()

test_df.head()

"""### Why We Check VIF and Drop Highly Correlated Features in Logistic Regression

- Logistic Regression is a linear model that assumes features are independent.
- Multicollinearity (high correlation between features) can:
  - Cause unstable and unreliable coefficient estimates.
  - Inflate standard errors and reduce model interpretability.
  - Lead to overfitting and poor generalization.
- Variance Inflation Factor (VIF) is used to detect multicollinearity.
  - A VIF value >5 or >10 indicates high multicollinearity.
- Based on VIF and correlation matrix analysis:
  - We dropped `Fare` because it is highly correlated with `Pclass`.
  - We dropped `Title_Mr` because it is highly correlated with `Sex_male`.
- This helps to:
  - Stabilize model coefficients.
  - Improve model generalization on unseen data.
  - Maintain model simplicity and interpretability.

"""

# Convert all boolean columns in test_df to int
test_df = test_df.astype({col: 'int64' for col in test_df.select_dtypes(include='bool').columns})

# Match column order to train_df (excluding 'Survived')
# Get the feature column order from train_df (excluding target)
feature_order = train_df.drop('Survived', axis=1).columns.tolist()

# Reorder test_df columns
test_df = test_df[feature_order]

# Final check
print(test_df.head())

"""### Separate features (X) and target (y)"""

# Separate features (X) and target (y)
X = train_df.drop('Survived', axis=1)
y = train_df["Survived"]               # only the target column

"""## Build Logistic regression Model"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.model_selection import train_test_split

# Split into training and test/validation sets
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""### Standardization"""

from sklearn.preprocessing import StandardScaler

# Define numerical columns to scale
num_cols_to_scale = ['Age', 'Parch']

# Fit scaler on x of train dataset
scaler = StandardScaler()
x_train[num_cols_to_scale] = scaler.fit_transform(x_train[num_cols_to_scale])
# Apply the same scaler to test set
x_test[num_cols_to_scale] = scaler.transform(x_test[num_cols_to_scale])

# Apply the same scaler to test dataset
test_df[num_cols_to_scale] = scaler.transform(test_df[num_cols_to_scale])

model = LogisticRegression()
model.fit(x_train, y_train)

#Now predict on the validation set (we know the actual labels here!)
y_pred = model.predict(x_test)

x_test.head()

test_df.head()

"""### Model prediction for test data"""

# predion of survived for test data set
test_preds = model.predict(test_df)

"""## Model Evaluation:"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Precision
print("Precision:", precision_score(y_test, y_pred))

# Recall
print("Recall:", recall_score(y_test, y_pred))

# F1 Score
print("F1 Score:", f1_score(y_test, y_pred))

# ROC-AUC (needs probabilities)
y_proba = model.predict_proba(x_test)[:, 1]
print("ROC AUC Score:", roc_auc_score(y_test, y_proba))

"""**🔍 Model Evaluation Summary**

After training the Logistic Regression model, we evaluated its performance using various classification metrics on the validation set (20% split from the original training data):

- **Accuracy**: Measures how many total predictions were correct.  
- **Precision**: Of all passengers predicted to survive, how many actually did.  
- **Recall**: Of all actual survivors, how many did the model correctly identify.  
- **F1-Score**: A balance between precision and recall.  
- **ROC AUC Score**: Measures the model's ability to distinguish between survived and not survived.

| Metric       | Value      |
|--------------|------------|
| Accuracy     | 84.90%     |
| Precision    | 83.87%     |
| Recall       | 78.78%     |
| F1 Score     | 81.25%     |
| ROC AUC      | 87.91%     |

These scores indicate that the logistic regression model performs well on the Titanic dataset, especially in terms of distinguishing survivors from non-survivors (ROC AUC = 87.91%).

"""

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_test, y_proba)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label="ROC Curve", color='blue')
plt.plot([0, 1], [0, 1], 'k--', label="Random Guess")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid(True)
plt.show()

"""**📈 ROC Curve Interpretation**

The ROC curve plots the **True Positive Rate** (Recall) vs the **False Positive Rate** at various classification thresholds.

- A curve that bends toward the top-left corner indicates a strong model.
- The **area under the curve (AUC)** was 0.87, which shows excellent classification ability.

The curve clearly shows that the model is much better than random guessing (represented by the dashed diagonal line).

## Interpretation:
"""

# Extract coefficients and features
coeff_df = pd.DataFrame({
    'Feature': x_train.columns,
    'Coefficient': model.coef_[0]
})

# Calculate absolute values for importance
coeff_df['Abs(Coefficient)'] = np.abs(coeff_df['Coefficient'])

# Sort by importance
coeff_df = coeff_df.sort_values(by='Abs(Coefficient)', ascending=False)

# Display
coeff_df[['Feature', 'Coefficient']]

"""## 📋 Interpretation of Logistic Regression Coefficients

After training the Logistic Regression model, we analyzed the learned coefficients to understand the influence of each feature on the survival prediction.

- **Positive Coefficient** ➔ Increases the probability of survival.
- **Negative Coefficient** ➔ Decreases the probability of survival.
- **Larger magnitude** ➔ Stronger impact on survival prediction.

Here is the interpretation based on the model's coefficients:

| Feature        | Coefficient | Interpretation |
|----------------|-------------|----------------|
| Sex_male       | -2.91        | Being male significantly decreases survival probability. |
| Title_Master   | +1.85        | Having the title 'Master' (young boys) increases survival chances. |
| Pclass         | -1.12        | Higher passenger class (lower class number) decreases survival chance. |
| Title_Miss     | -0.58        | Title 'Miss' has a slight negative impact compared to other features. |
| Age            | -0.33        | Older age slightly decreases survival probability. |
| Parch          | -0.29        | Having parents/children aboard slightly decreases survival probability. |
| Title_Ms       | +0.11        | Title 'Ms' slightly increases survival chances. |
| Title_Mme      | +0.06        | Title 'Mme' has minimal positive influence on survival. |

---

✅ **Key Insights:**
- **Sex_male** has the strongest negative effect (being male reduces survival probability).
- **Title_Master** shows strong positive impact (young boys had higher survival chances).
- **Pclass** indicates that lower class passengers had lower chances of survival.


---

"""

